name: Upload Docker Image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.*'  # Trigger on tags like v1.0, 2.3, etc.

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login
        run: docker login -u "${{ secrets.USERNAME }}" -p "${{ secrets.TOKEN }}"

      - name: Build
        run: |
          DOCKER_IMAGE_TAG="${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}"
          docker build -t "$DOCKER_IMAGE_TAG" .
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
              docker tag "$DOCKER_IMAGE_TAG" "${GITHUB_REPOSITORY}:latest"
          fi

      - name: Publish Docker image
        run: |
          DOCKER_IMAGE_TAG="${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}"
          docker push "$DOCKER_IMAGE_TAG"
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
              docker push "${GITHUB_REPOSITORY}:latest"
          fi
