name: Upload Python Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'  # Trigger on tags like v1.0, 2.3, etc.

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
